apiVersion: skaffold/v2beta29
kind: Config
build:
  tagPolicy:
    sha256: { }
  artifacts:
    - image: public.ecr.aws/v7z3c3p2/controller
      context: .
    - image: public.ecr.aws/v7z3c3p2/ecr-token-refresh
      context: ecrtokenrefresher/
deploy:
  helm:
    releases:
      - name: eksa-controller
        recreatePods: false
        skipBuildDependencies: false
        useHelmSecrets: false
        wait: false
        chartPath: charts/eks-anywhere-packages
        imageStrategy:
          #helm: {}
          helm:
            explicitRegistry: true
        setValues:
          clusterName: "dev-cluster"
          sourceRegistry: "public.ecr.aws/v7z3c3p2"
          cronjob.tag: "latest"
          controller.tag: "latest"
          controller.repository: "controller"
          cronjob.suspend: "true"
          podSecurityContext:
            runAsNonRoot: false